# Generated by Django 4.0.1 on 2022-01-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
                ('car', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('total_votes', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartage.address')),
            ],
        ),
        migrations.RemoveField(
            model_name='dummyteacher',
            name='address',
        ),
        migrations.DeleteModel(
            name='DummyStudent',
        ),
        migrations.DeleteModel(
            name='DummyTeacher',
        ),
    ]
