# Generated by Django 4.0.1 on 2022-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartage', '0002_user_remove_dummyteacher_address_delete_dummystudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car',
            field=models.BooleanField(),
        ),
    ]
