# Generated by Django 4.0.1 on 2022-01-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartage', '0003_alter_user_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='madeByTeacher',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to='cartage.user'),
        ),
        migrations.AddField(
            model_name='trip',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to='cartage.user'),
        ),
    ]
